apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: application-spring-cloud-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      namespace: dev
      app: application-spring-cloud-eureka
  template:
    metadata:
      labels:
         namespace: dev
         app: application-spring-cloud-eureka
    spec:
      containers:
      - name: application-spring-cloud-eureka
        imagePullPolicy: Always
        image: registry.cn-beijing.aliyuncs.com/application-spring-cloud/eureka:v2
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: application-spring-cloud-eureka
  namespace: dev
spec:
  ports:
   - port: 80
     protocol: TCP
     targetPort: 80
  selector:
    namespace: dev
    app: application-spring-cloud-eureka
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dev
  name: application-spring-cloud-eureka
spec:
  rules:
  - host: eureka.yulece.com
    http:
      paths:
      - path: /
        backend:
          serviceName: application-spring-cloud-eureka
          servicePort: 80
