server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${ADMIN_PMS_MYSQL_HOST_SERVICE_ENDPOINT}:${ADMIN_PMS_MYSQL_PORT_SERVICE_ENDPOINT}/application_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&&allowPublicKeyRetrieval=true
    username: ${ADMIN_PMS_MYSQL_USERNAME_SERVICE_ENDPOINT}
    password: ${ADMIN_PMS_MYSQL_PASSWORD_SERVICE_ENDPOINT}
  redis:
    host: ${REDIS_HOST_SERVICE_ENDPOINT}
    port: ${REDIS_PORT_SERVICE_ENDPOINT}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_ENDPOINT}/eureka