server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://140.143.234.53:3306/application_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&&allowPublicKeyRetrieval=true
    username: admin
    password: 19940509WYC@
  redis:
    host: 140.143.234.53
    port: 6999
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka