spring:
  application:
    name: app-async-provider
  profiles:
    active: dev
ALIYUN_MAIL_ACCESSKEY: XXXXXX
ALIYUN_MAIL_ACCESSSECRET: XXXXXX
ALIYUN_MAIL_FROMALIAS: OA服务平台
ALIYUN_MAIL_HOST: admin@mail.yulece.com